### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Makos305** [ShimmyMySherbet/MusixClient#4]
After i click download button, app just crashes. I tried both methods (search and manual). Any solution? Should I attach some log file? (I don't know where it is located)

**Comment by ShimmyMySherbet** [comment]
This will be an issue with the Youtube client being out-dated. Before full release, I will be adding an auto-updater for the youtube client to prevent this issue. Every now and then YouTube changes how its system works which breaks these clients. I already have a later version I'll release shortly with an updated youtube client.

**Comment by vincetota** [comment]
Hello, is the latest version still not released? I tried the app but after i click download button it crashes...

**Comment by ShimmyMySherbet** [comment]
This is again an issue with the Youtube client being outdated. I'll push a release now, though in future versions it will auto update.

**Comment by vincetota** [comment]
Great thank you!

**Comment by ShimmyMySherbet** [comment]
Just checked out the issue, and it looks like youtube has just recently changed their playlist model, meaning the youtube client Musix uses, YoutubeExplode, needs to be updated. It usually doesn't take too long, and I'll keep an eye out for the update.

**Comment by ShimmyMySherbet** [comment]
Just a quick update, the issue with YoutubeExplode has not been fixed. I'm going to look at replacing the currently broken features natively in Musix.

**Comment by ShimmyMySherbet** [comment]
I've finally gotten around to doing some major fixes to the app.
You can download the latest version here: https://github.com/ShimmyMySherbet/MusixClient/releases
Open another issue if you have any problems with it.
